<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not put any code except 'define' operations
 * as it could be overwritten.
 * Instead, use the Mouf User Interface to set all your constants: http://[server]/sandbox/moufla/vendor/mouf/mouf/../../../mouf/config
 */

/**
 * Set to true to enable debug/development mode.
 */
define('DEBUG', true);
/**
 * A random string. It should be different for any application deployed.
 */
define('SECRET', 'yM6IUrqFK6SM3rmSrZME');
